export type TerraNutritionPayload = {
    metadata?: {
        start_time?: string | null;
        end_time?: string | null;
        /** Optional client-provided identifier (e.g. ME24 guid) for round-tripping. */
        me24_id?: string | null;
    } | null;
    summary?: {
        macros?: {
            sodium_mg?: number | null;
            protein_g?: number | null;
            carbohydrates_g?: number | null;
            fiber_g?: number | null;
            cholesterol_mg?: number | null;
            fat_g?: number | null;
            saturated_fat_g?: number | null;
            trans_fat_g?: number | null;
            sugar_g?: number | null;
            calories?: number | null;
            alcohol_g?: number | null;
            net_carbohydrates_g?: number | null;
        } | null;
        micros?: {
            biotin_mg?: number | null;
            caffeine_mg?: number | null;
            chloride_mg?: number | null;
            chromium_mg?: number | null;
            copper_mg?: number | null;
            calcium_mg?: number | null;
            folate_mg?: number | null;
            folic_acid_mg?: number | null;
            iodine_mg?: number | null;
            iron_mg?: number | null;
            magnesium_mg?: number | null;
            manganese_mg?: number | null;
            molybdenum_mg?: number | null;
            niacin_mg?: number | null;
            pantothenic_acid_mg?: number | null;
            phosphorus_mg?: number | null;
            potassium_mg?: number | null;
            riboflavin_mg?: number | null;
            selenium_mg?: number | null;
            thiamin_mg?: number | null;
            vitamin_A_mg?: number | null;
            vitamin_B12_mg?: number | null;
            vitamin_B6_mg?: number | null;
            vitamin_C_mg?: number | null;
            vitamin_D_mg?: number | null;
            vitamin_E_mg?: number | null;
            vitamin_K_mg?: number | null;
            vitamin_D3_mg?: number | null;
            vitamin_D2_mg?: number | null;
            zinc_mg?: number | null;
            starch_g?: number | null;
            omega3_g?: number | null;
            omega6_g?: number | null;
            cystine_g?: number | null;
            histidine_g?: number | null;
            isoleucine_g?: number | null;
            leucine_g?: number | null;
            lysine_g?: number | null;
            methionine_g?: number | null;
            phenylalanine_g?: number | null;
            threonine_g?: number | null;
            tryptophan_g?: number | null;
            tyrosine_g?: number | null;
            valine_g?: number | null;
            monounsaturated_fat_g?: number | null;
            polyunsaturated_fat_g?: number | null;
        } | null;
        water_ml?: number | null;
        drink_ml?: number | null;
    } | null;
};
